image: ubuntu:20.04

stages:
    - test

test:
    stage: test
    script:
        - apt -y update && apt -y install python3-pip
        - pip install .[test]
        - flake8
        - python3 setup.py test
