image: ubuntu:20.04

stages:
    - test

test:
    stage: test
    script:
        - sudo apt update && sudo apt install python3-pip
        - pip install .[test]
        - flake8
        - python setup.py test
