image: python:alpine

stages:
    - test
    - tox

test:
    stage: test
    script:
        - pip install .[test]
        - flake8
        - python setup.py test

tox:
    stage: tox
    script:
        - apk add python3.6
        - apk add python3.7
        - apk add python3.8
        - pip install tox
        - pip install .[test]
        - tox
