image: snakepacker/python

stages:
    - test

test:
    stage: test
    script:
        - apt -y install python3-pip
        - pip install .[test]
        - pip install tox
        - flake8
        - tox
