image: python:alpine

stages:
 - test

test:
    stage: deploy
    script:
        - sudo apt-get install python3-pip
        - sudo pip3 install virtualenv
        - virtualenv venv
        - virtualenv -p python3 venv
        - source venv/bin/activate
        - pip install -r requirements.txt
        - pytest
