image: python:alpine

before_script:
    - pip install -r requirements.txt

stages:
    - test

test:
    stage: test
    script:
        - flake8 --max-line-length=120
        - python -m unittest -v -b
